kind = "web"
previewPath = "/"
title = "FLASHYAF™"
version = "1.0.0"
id = "artifacts/flashyaf"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22559

[services.development]
run = "pnpm --filter @workspace/flashyaf run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/flashyaf", "run", "build" ]
publicDir = "artifacts/flashyaf/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22559"
BASE_PATH = "/"
